version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - /volume1/docker/airflow/pg:/bitnami/postgresql
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /volume1/docker/airflow/redis:/bitnami
  airflow-worker:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_COMPONENT_TYPE=worker
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW__SMTP__SMTP_HOST=sandbox.smtp.mailtrap.io
      - AIRFLOW__SMTP__SMTP_USER=d38854e2ff85d0
      - AIRFLOW__SMTP__SMTP_PASSWORD=<pass removed>
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=teszt@teszt.com
      - AIRFLOW__SMTP__SMTP_PORT=2525
    volumes:
      - /volume1/docker/airflow/dag:/opt/bitnami/airflow/dags
      - /volume1/docker/airflow/requirements.txt:/bitnami/python/requirements.txt
  airflow-scheduler:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_COMPONENT_TYPE=scheduler
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW__SMTP__SMTP_HOST=sandbox.smtp.mailtrap.io
      - AIRFLOW__SMTP__SMTP_USER=d38854e2ff85d0
      - AIRFLOW__SMTP__SMTP_PASSWORD=<pass removed>
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=teszt@teszt.com
      - AIRFLOW__SMTP__SMTP_PORT=2525
    volumes:
      - /volume1/docker/airflow/dag:/opt/bitnami/airflow/dags
      - /volume1/docker/airflow/requirements.txt:/bitnami/python/requirements.txt
  airflow:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW__SMTP__SMTP_HOST=sandbox.smtp.mailtrap.io
      - AIRFLOW__SMTP__SMTP_USER=d38854e2ff85d0
      - AIRFLOW__SMTP__SMTP_PASSWORD=<pass removed>
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=teszt@teszt.com
      - AIRFLOW__SMTP__SMTP_PORT=2525
    volumes:
      - /volume1/docker/airflow/dag:/opt/bitnami/airflow/dags
      - /volume1/docker/airflow/requirements.txt:/bitnami/python/requirements.txt
    ports:
      - '12660:8080'